module.exports = {
    apps: [
      // {
      //   name: "Cexpcex",
      //   script: "./cexpcex",
      //   instances: 1,
      //   autorestart: true,
      //   watch: false,
      //   max_memory_restart: "200M",
      // },
      {
        name: "Dot",
        script: "./dotcoin",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Oxygen",
        script: "./oxygen",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Pocketgame",
        script: "./pocketgame",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Timefarm",
        script: "./timefarm",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Timefarm6h",
        script: "./timefarm-6h",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Wigwam-drum",
        script: "./wigwam-drum",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Onus",
        script: "./onusTap",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Seed",
        script: "./seed",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
      {
        name: "Ocean-6",
        script: "./ocean-6.js",
        instances: 1,
        autorestart: true,
        watch: false,
        max_memory_restart: "200M",
      },
    ],
  };
  